get:
    operationId: getSharedAssessmentConfig
    summary: Get the configuration JSON for a shared assessment app context.
    tags: 
        - Shared Assessments
        - Public
    security:
        - BridgeSecurity: []
    parameters:
        - $ref: ../../index.yml#/parameters/guid
    responses:
        200:
            description: OK
            schema:
                $ref: ../../definitions/assessment_config.yml
        304:
            $ref: ../../responses/304.yml
        401:
            $ref: ../../responses/401.yml

