swagger: '2.0'
info:
    version: "0.24.9"
    title: Bridge Server API
host: webservices.sagebridge.org
basePath: /
securityDefinitions:
    BridgeSecurity:
        type: apiKey
        in: header
        name: Bridge-Session
schemes:
    - https
consumes:
    - application/json
produces:
    - application/json
parameters:
    assessmentId:
        name: assessmentId
        description: The identifier for a stream of assessment revisions
        required: True
        in: path
        type: string
    cacheKey:
        name: cacheKey
        description: Cache key
        required: true
        in: path
        type: string
    consents:
        name: consents
        description: Should consent histories be included with this participant record?
        required: false
        in: query
        type: boolean
    eventId:
        name: eventId
        description: An activity event key
        required: true
        in: path
        type: string
    externalId:
        name: externalId
        description: User's external ID
        required: true
        in: path
        type: string
    fileId:
        name: fileId
        required: true
        in: path
        type: string
    synapseUserId:
        name: synapseUserId
        description: User's Synapse user ID
        required: true
        in: path
        type: string
    moduleId:
        name: moduleId
        description: Unique ID of the module.
        required: true
        in: path
        type: string
    moduleVersion:
        name: moduleVersion
        description: Module version.
        required: true
        in: path
        type: integer
    orgId:
        name: orgId
        description: Organization ID
        required: true
        in: path
        type: string
    reportId:
        name: reportId
        description: Report ID
        required: true
        in: path
        type: string
    schemaId:
        name: schemaId
        description: Upload schema ID
        required: true
        in: path
        type: string
    taskId:
        name: taskId
        description: Task ID
        required: true
        in: path
        type: string
    version:
        name: version
        description: version number
        required: true
        in: path
        type: integer
    revision:
        name: revision
        description: Revision number
        required: true
        in: path
        type: integer
        format: int64
    scheduleGuid:
        name: scheduleGuid
        description: Schedule GUID
        required: true
        in: path
        type: string
    scheduleId:
        name: scheduleId
        description: Scheduler identifier
        required: true
        in: path
        type: string
    schedulePlanGuid:
        name: schedulePlanGuid
        description: Schedule plan GUID
        required: true
        in: path
        type: string
    subpopulationGuid:
        name: subpopulationGuid
        description: Subpopulation GUID
        required: true
        in: path
        type: string
    appId:
        name: appId
        description: App ID
        required: true
        in: path
        type: string
    recordId:
        name: recordId
        description: Health data record ID
        required: true
        in: path
        type: string
    studyId:
        name: studyId
        description: Study identifier
        required: true
        in: path
        type: string
    tag:
        name: tag
        required: false
        in: query
        type: array
        items:
            type: string
        collectionFormat: multi
        description: One or more tags. Every resource that has at least one of the tags will be returned (resources do not need to match all tags).
    uploadId:
        name: uploadId
        description: Upload ID
        required: true
        in: path
        type: string
    userId:
        name: userId
        description: User ID
        required: true
        in: path
        type: string
    surveyGuid:
        name: surveyGuid
        description: Survey GUID
        required: true
        in: path
        type: string
    createdOn:
        name: createdOn
        description: Created on timestamp (ISO 8601)
        required: true
        in: path
        type: string
        format: date-time
    createdOnStart:
        name: createdOnStart
        description: Start time (ISO 8601) for a createdOn date-time range
        required: false
        in: query
        type: string
        format: date-time
    createdOnEnd:
        name: createdOnEnd
        description: End time (ISO 8601) for a createdOn date-time range
        required: false
        in: query
        type: string
        format: date-time
    newSchemaRev:
        name: newSchemaRev
        description: Should a new schema revision be created?
        required: false
        in: query
        type: boolean
    identifier:
        name: identifier
        description: identifier
        required: true
        in: path
        type: string
    enrollmentFilter:
        name: enrollmentFilter
        description: Filter enrollees
        required: false
        in: query
        type: string
        enum: [enrolled,withdrawn,all]
    includeTesters:
        name: includeTesters
        description: Include accounts with 'test_user' data group
        required: false
        default: false
        in: query
        type: boolean
    startDate:
        name: startDate
        in: query
        description: The first day to include in reports that are returned
        type: string
        format: date 
        required: true
    endDate:
        name: endDate
        in: query
        description: The last day to include in reports that are returned
        type: string 
        format: date
        required: true
    startTime:
        name: startTime
        in: query
        type: string
        format: date-time
        required: true
    endTime:
        name: endTime
        in: query
        type: string
        format: date-time
        required: true
    startTimeOpt:
        name: startTime
        in: query
        description: The first day to include in reports that are returned
        type: string
        format: date-time
        required: false
    endTimeOpt:
        name: endTime
        in: query
        description: The last day to include in reports that are returned
        type: string
        format: date-time
        required: false
    pageSize:
        name: pageSize
        description: maximum number of records in each returned page
        in: query
        type: integer
        format: int32
        required: false
        default: 50
        maximum: 100
    offsetBy:
        name: offsetBy
        description: next page start offset for pagination 
        in: query
        type: integer
        format: int32
        default: 0
        required: false
    offsetKey:
        name: offsetKey
        description: next page start key for pagination 
        in: query
        type: string
        required: false
    guid:
        name: guid
        description: A guid
        required: true
        in: path
        type: string
    activityGuid:
        name: activityGuid
        description: Activity GUID
        required: true
        in: path
        type: string
    scheduledOnStart:
        name: scheduledOnStart
        in: query
        description: |
            Activities returned are at or after the timestamp. If scheduledOnStart is 
            provided, scheduledOnEnd must be provided, and vice versa. Default range is 
            4 days in the future to 10 days in the past.
        type: string
        format: date-time
        required: false
    scheduledOnEnd:
        name: scheduledOnEnd
        in: query
        description: |
            Activities returned are at or before the timestamp. If scheduledOnEnd is 
            provided, scheduledOnStart must be provided, and vice versa. Default range is 
            4 days in the future to 10 days in the past.
        type: string 
        format: date-time
        required: false
    emailFilter:
        name: emailFilter
        description: |
            A string (can be a substring of an email address) to filter returned records against.
        in: query
        type: string
        required: false
    phoneFilter:
        name: phoneFilter
        description: |
            A string (can be a substring of a phone number) to filter returned records against.
        in: query
        type: string
        required: false
    vendorId:
        name: vendorId
        description: OAuth 2.0 provider ID
        required: true
        in: path
        type: string
    healthCode:
        name: healthCode
        description: User health code
        required: true
        in: path
        type: string
    physical:
        name: physical
        description: Physically delete this resource? (administrators only; this is always false for developers)
        default: false
        required: false
        in: query
        type: boolean
    includeDeleted:
        name: includeDeleted
        description: Should deleted items be returned in results?
        required: false
        in: query
        default: false
        type: boolean
    mostrecent:
        name: mostrecent
        in: query
        type: boolean
        required: false
        default: true
        description: |
            True to get only the most recent versions. If combined with published=true, then this will return the most recent published versions. Cannot be combined with where. Defaults to true.
    name:
        name: name
        in: query
        type: string
        required: false
        description: String to match anywhere in the name field of the shared module record.
    notes:
        name: notes
        in: query
        type: string
        required: false
        description: String to match anywhere in the notes field of the shared module record.
    published:
        name: published
        in: query
        type: boolean
        required: false
        default: false
        description: Should the shared module record be published?
    id:
        name: id
        in: path
        type: string
        required: true
        description: An identifier
    tags:
        name: tags
        in: query
        type: string
        required: false
        description: |
              Comma-delimited list of tags. If specified, only query results that match one or more tags (not necessarily all tags) are returned. If not specified, returns all query results.
    tagValue:
        name: tagValue
        description: A tag value
        required: true
        in: path
        type: string
    templateType:
        name: type
        in: query
        type: string
        enum: [email_account_exists, email_app_install_link, email_reset_password, email_sign_in, email_signed_consent, email_verify_email, sms_account_exists, sms_app_install_link, sms_phone_sign_in, sms_reset_password, sms_signed_consent, sms_verify_phone]
    category:
        name: category
        in: query
        type: array
        items:
            type: string
            enum: [customization_options, data_repository, science_documentation, developer_documentation, license, publication, release_note, sample_app, sample_data, screenshot, see_also, used_in_study, website, other]
        collectionFormat: multi
        description: One or more category values. Searches specifying more than one category will return a resource if it matches *any* of the categories given (it does not need to match all of them).
    minRevision:
        name: minRevision
        in: query
        type: integer
        format: int32
        description: If this parameter is set, only resoures with a `createdAtRevision` value >= minRevision will be returned from the API (if the parameter is left null, all resources will be considered to match).
    maxRevision:
        name: maxRevision
        in: query
        type: integer
        format: int32
        description: If this parameter is set, only resources with a `createdAtRevision` value <= maxRevision will be returned from the API (if the parameter is left null, all resources will be considered to match).
    withdrawalNote:
        name: withdrawalNote
        in: query
        type: string
        description: The reason given for a user’s withdrawal from a study.
    parentId:
        name: parentId
        in: query
        type: string
        description: The id used in place of appId, and in the future, studyId.
    instanceGuid:
        name: instanceGuid
        description: Instance GUID of the adherence record
        required: true
        in: path
        type: string
    eventTimestamp:
        name: eventTimestamp
        description: Event timestamp (ISO 8601) of the adherence record
        required: true
        in: path
        type: string
        format: date-time
    startedOn:
        name: startedOn
        description: Starting timestamp (ISO 8601) of the adherence record
        required: true
        in: path
        type: string
        format: date-time
    showError:
        name: showError
        description: Return a 400 status if the submission cannot be persisted
        required: false
        in: query
        type: boolean
        default: false
    updateBursts:
        name: updateBursts
        description: If this event is an originating event for a study burst, update the study burst events (while following their update type rules)
        required: false
        in: query
        type: boolean
        default: true
    entityType:
        name: entityType
        description: The type of entity that a permission record is addressing.
        required: true
        in: path
        type: string
        enum: [ assessment, assessment_library, members, organization, participants, sponsored_studies, study, study_pi ]
    entityId:
        name: entityId
        description: The ID of the entity that a permission record grants access to.
        required: true
        in: path
        type: string
paths:
    $ref: ./paths/index.yml
definitions:
    $ref: ./definitions/index.yml
responses:
    $ref: ./responses/index.yml
    
