get:
    operationId: getAssessmentConfigForWorker
    summary: Get the JSON config for this assessment.
    tags:
        - Assessments
        - _For Workers
    security:
        - BridgeSecurity: []
    parameters:
        - $ref: ../../index.yml#/parameters/appId
        - $ref: ../../index.yml#/parameters/guid
    responses:
        200:
            description: OK
            schema:
                $ref: ../../definitions/assessment_config.yml
        401:
            $ref: ../../responses/401.yml
        403:
            $ref: ../../responses/403_not_worker.yml
