package org.sagebionetworks.bridge.sdk;

public enum SharingScope {
    /**
     * Don't export data generated by this participant.
     */
    no_sharing,
    /**
     * Only export data for this participant to data sets that are restricted to the original 
     * study researchers and their affiliated research partners.
     */
    sponsors_and_partners,
    /**
     * Data for this participant can be exported for use by any researcher who qualifies given
     * the governance qualifications of this data set.
     */
    all_qualified_researchers

}
